### ISSUE TITLE
features suggestions

### ISSUE THREAD

**Issue by kaveinthran** [craigbrett17/Blindspot#24]
1. will be nice if there are preloaded buffers such as artist, home, saved songs and albums buffers besides the playlist buffer when first loaded.
2. search by every category possible or all categories including users public playlist
3. spesifying quality of music
4. getting url for playlist, album or artist
5. support jaws feedback
6. control properties of tts

7. be able to see our release radars and other personalised things from spotify

**Comment by rkingett** [comment]
These are all great suggestions! I would also add support for radio 
stations? Or getting the URL for these stations or even the embed codes 
for these playlists too?

**Comment by kaveinthran** [comment]
yeah sure, will be wonderful to look forward to the future, wil be
nice to have guie coming up!

**Comment by craigbrett17** [comment]
Hi @kaveinthran, I'll probably split these out into their own issues, as I can't track all of these in one batch, as some of these could be quite tough. And scheduling everything to be available on any given release will not work.

Several of these, like displaying a home tab, release radars, etc, might well be locked down to Spotify's own stuff, because business, I assume. Either that, or they won't be available publically, and are just in Spotify's own source code for their desktop and mobile apps, as opposed to being available on what we use. Some of these are things I believe I can fix though. I'll ask for more specific info on each issue.
